# 
# Do not Edit! Generated by:
# spectacle version 0.13~pre
# 
# >> macros
# << macros

Name:       diffstat
Summary:    A utility which provides statistics based on the output of diff
Version:    1.46
Release:    1
Group:      Development/Tools
License:    MIT
URL:        http://invisible-island.net/diffstat
Source0:    ftp://invisible-island.net/diffstat/%{name}-%{version}.tgz
Source1:    COPYING
Source100:  diffstat.yaml

BuildRoot:  %{_tmppath}/%{name}-%{version}-build

%description
The diff command compares files line by line.  Diffstat reads the
output of the diff command and displays a histogram of the insertions,
deletions and modifications in each file.  Diffstat is commonly used
to provide a summary of the changes in large, complex patch files.

Install diffstat if you need a program which provides a summary of the
diff command's output.




%prep
%setup -q -n %{name}-%{version}
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
# Call make instruction with smp support
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install
mkdir -p %{buildroot}/usr/share/doc/diffstat/
cp -a %{SOURCE1} %{buildroot}/usr/share/doc/diffstat/


# >> install post
# << install post

%clean
rm -rf %{buildroot}






%files
%defattr(-,root,root,-)
# >> files
%doc /usr/share/doc/diffstat/COPYING
%{_bindir}/diffstat
%{_mandir}/*/*
# << files


